### PR TITLE
fix current version detection

### PR DESCRIPTION
**Pull request by Skywalker-11**
Discussed in #60

### CODE REVIEW

**Comment by ghost** [comment]
@Skywalker-11 This is a much better method.  Should the same be done with MailScanner?

**Comment by Skywalker-11** [comment]
> @Skywalker-11 This is a much better method. Should the same be done with MailScanner?

Problem is that MS doesn't publish the  .deb's/.rpm's at the same time as the source code release

**Comment by ghost** [comment]
@Skywalker-11 Make sense.

**Comment by Skywalker-11** [comment]
@shawniverson btw. is there a reason they aren't published on github together with the source code?

**Comment by ghost** [comment]
@Skywalker-11 Nope, but they are small, and I will gladly do that if it helps.

**Pull request merged**
