### PR TITLE
Updated OS detection to for better compatibility

### PR DESCRIPTION
**Pull request by asuweb**
Updated OS detection to for better compatibility
Added OS version identification for CentOS
Added MariaDB repos for yum (centos)
Corrected MariaDB install commands for CentOS

### CODE REVIEW

**Comment by asuweb** [comment]
Need to test on RedHat / Fedora

Need to check if there are any installation differences between Debian / Ubuntu versions and add checks where neccessary

**Comment by ghost** [comment]
@asuweb Does/will MailWatch require the use of MariaDB beyond the version included in CentOS 7 in particular.  Curious about the addition of the MariaDB repo...

**Comment by Skywalker-11** [comment]
It should also work with mysql but theres an open bug which seems to be resolved by using MariaDB instead of MySQL: mailwatch/1.2.0#428

**Comment by asuweb** [comment]
@shawniverson - probably not, however the MariaDB 10 brings certain improvement in InnoDB performance especially.  

Is there a reason not to use the latest version on fresh installs (where there is no mysql/mariadb installed already)?

Centos 5/6 doesn't have mariadb by default, where as centos 7 has MariaDB 5 as standard.

I don't mind either way, we can revert to MariaDB 5 if people prefer?

I think we picked MariaDB due to the bug mentioned by @Skywalker-11

**Comment by stefaweb** [comment]
@Skywalker-11 

I'm waiting for the feedback from @DiederikvandenB on this.

**Comment by ghost** [comment]
@asuweb -- Performance improvements are always good, and there's something to be said about having a consistent DB backend version across CentOS versions.  That alone may be worth going ahead and doing it this way.

**Comment by asuweb** [comment]
@shawniverson - I agree.  If everyone is using consistent versions, it will hopefully help with ongoing support

**Comment by stefaweb** [comment]
Be careful with https://github.com/mailwatch/1.2.0/issues/428. They use mixed version of RC4 and dev. We don't know exactly if all is ok on their side.

**Comment by asuweb** [comment]
@stefaweb - I suspect half the problem with majority of these bugs is due to mixing versions or "partial upgrades" - which hopefully with the completion of this script should be minimised in future

**Comment by stefaweb** [comment]
The error they got is a typical of sending wrong characters to the database. We had this error with 'subject' before adding fix_latin() to it.

```
Error：
Jan 23 09:03:50 mg1 MailScanner[13818]: Could not use Custom Function code MailScanner::CustomConfig::InitMailWatchLogging, it could not be "eval"ed. Make sure the module is correct with perl -wc (Error: DBD::mysql::st execute failed: Incorrect string value: '\xBCw\xA9g\xAFM...' for column 'headers' at row 1 at /usr/share/MailScanner/perl/custom/MailWatch.pm line 138, line 439.
```

I added fix_latin() to 'headers' in #556.

**Comment by ghost** [comment]
I know people clone the latest develop, which is a bad thing to do unless you are developing and puts you in a bad place when things go wrong or you get caught in the middle of fixes in progress...

Hence why I've been sitting back on RC4 for a while now, which has been reasonably stable despite lack of major improvements.  Looking forward to testing RC5 soon :)

**Comment by asuweb** [comment]
@shawniverson - yes, I guess people want the new features before we've had the time to properly test them and are ready to support them.

RC5 should be soon, and then 1.2 stable (finally!).

There's some good stuff in RC5 - V2 will be even better

**Comment by stefaweb** [comment]
I spent many many time to track bugs. I'm sure they will be close to zero in RC5.

**Comment by stefaweb** [comment]
Who is merging this?

IMPORTANT: I've already changed the name of `mailwatch.conf` in `00_mailwatch.conf` in `develop`.

**Comment by ghost** [comment]
Not sure.

**Comment by Skywalker-11** [comment]
is it ready for merge?

**Comment by asuweb** [comment]
There's no real advantage to merging the pr until it's finished.  But I'll merge it if you want?

**Comment by stefaweb** [comment]
If it does not bother you, can you merge it? It's more convenient to see the actual code in full.

**Pull request merged**
